### ISSUE TITLE
Will this project be continued?

### ISSUE THREAD

**Issue by zaaack** [ts-llvm/ts-llvm#2]
I have to say this is exactly the wasm solution for typescript that I'm looking for, @emlai  great job! 👍  But I also notice this project has been stopped for 3 months, would this project be continued?

**Comment by Kingwl** [comment]
@emlai thanks for the work, 

@zaaack and I are both interested in this project.

**Comment by emlai** [comment]
Hi! Glad to hear you're interested in this!

I'm doing this as a hobby project, so it all depends on my free time and motivation. This turned out to be quite a big project, so it's pretty overwhelming to work on it as a one-person team, but I definitely plan to continue it at some point when I have the time and motivation.

In the meantime, I'm happy to review pull requests if anyone is willing to contribute!

**Comment by zaaack** [comment]
@emlai Is there any roadmap or plans for new contributers start？Although @Kingwl and I doesn't use llvm before, but we can learn. @Kingwl is really interested in contributing to your excellent project. Thanks!

**Comment by emlai** [comment]
Good idea! I'll write some design documentation and create GitHub issues for important tasks when I have time, likely next week. If you want to start before that, I think implementing any of the basic language features of TypeScript would be good place to start.

I have some experience with LLVM so I can help with it, just ask on the [ts-llvm Slack](https://join.slack.com/t/ts-llvm/shared_invite/enQtMzU4MjQwMjI4MzUzLTk3M2VjYWU4MjA3MzIxMGIxMTJkMDg0ODdlZWNlNzg1ZDBkMjRiMjJmMzc2ZDYwZTYxMTg3NzVlMmJlY2JiNDg) or create a GitHub issue. Also the llvm-node API is almost identical to the C++ API so any existing questions about using LLVM on StackOverflow or elsewhere should be useful for this project as well.

**Comment by emlai** [comment]
@zaaack @Kingwl Hey! I finally made the roadmap for language features. Check it out: #6 

Standard library roadmap will also come soon.
